version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    expose:
      - "2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app
  kafka:
    image: docker.io/bitnami/kafka:3
    expose:
      - "9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - app
  producer:
    build: ./pkg-gen-producer
    environment:
      - KAFKA_SERVERS=kafka:9092
    ports:
      - '3000:3000'
    networks:
      - app


networks:
  app: 
    driver: bridge 
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local